# ================================================================
#                        AFKRegions Configuration
# ================================================================
# Plugin for managing AFK regions with rewards and statistics
# Version: 1.0.2

# ================================================================
#                            GENERAL SETTINGS
# ================================================================
general:
  debug: false                    # Enable debug logging
  reset_on_exit: true            # Reset timer when leaving AFK region
  disable_item_interaction: true # Disable item pickup and dropping while in AFK regions

# ================================================================
#                         REGION DETECTION
# ================================================================
detection:
  region_check_interval: 10      # How often to check player positions (ticks) - 10 = 0.5s
  tick_interval: 20              # Reward/progress update interval (ticks) - 20 = 1s

# ================================================================
#                           USER INTERFACE
# ================================================================
ui:
  # Title Settings
  titles_enabled: true           # Enable/disable title messages
  titles_enter_exit: true        # Show titles when entering/exiting regions
  title_every_seconds: 1         # Title refresh interval (seconds)

  # Boss Bar Settings (1.9+)
  bossbar_enabled: true          # Enable/disable boss bar
  bossbar_title: "&bAFK &7in &f{region}&7 — &b{elapsed}&7/&f{max} &7({progress%}%)"
  bossbar_color: "BLUE"          # BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  bossbar_style: "SEGMENTED_10"  # Boss bar style

# ================================================================
#                            REWARDS
# ================================================================
rewards:
  message_enabled: true          # Send message when player receives reward

# ================================================================
#                           DATABASE
# ================================================================
database:
  enabled: false                 # Enable database storage for statistics
  host: "localhost"
  port: 3306
  database: "afkregions"
  username: "root"
  password: ""
  use_ssl: false

# ================================================================
#                          STATISTICS
# ================================================================
statistics:
  enabled: true                  # Enable statistics tracking
  auto_save_interval_minutes: 5  # Auto-save interval (minutes)