settings:
  debug: false
  titles_enabled: true
  titles_enter_exit: true    # Set false to disable the titles on entry/exit afk region
  title_every_seconds: 1      # Every how much seconds the title will be refreshed. recommended: 1
  reset_on_exit: true # Reset timer on exit of the afk region
  tick_interval: 20 # The update in ticks, 20 = 1s
  bossbar_enabled: true # Enable or disable the bossbar. +1.9 feature true/false
  bossbar_title: "&bAFK &7en &f{region}&7 — &b{elapsed}&7/&f{max} &7({progress%}%)"
  bossbar_color: "BLUE"   # BLUE, GREEN, PINK, PURPLE, RED, WHITE, YELLOW
  bossbar_style: "SEGMENTED_10" # Normally I do not recommend modifying this
